// Next
import type { Metadata } from "next";

// Recoil
import RecoilRootProvider from "@/recoil/RecoilRootProvider";

// Styles
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="ko">
      <body>
        <RecoilRootProvider>{children}</RecoilRootProvider>
        <div id="modal"></div>
      </body>
    </html>
  );
}
