// Next
import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";

// Components
import AlertModal from "@/components/common/AlertModal";

// Styles
import "@/styles/globals.css";

// Types
import { IPageProps } from "@/types/commonType";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: Pick<IPageProps, "children">) {
  return (
    <html>
      <body>
        <CookiesProvider>
          <AlertModal />
          {props.children}
        </CookiesProvider>
        <div id="modal"></div>
      </body>
    </html>
  );
}
