// Next
import type { Metadata } from "next";
import { useTranslation } from "@/i18n";
import { i18nNamespaces } from "@/i18n/i18nConfig";
import TranslationsProvider from "@/i18n/TranslationsProvider";
import { CookiesProvider } from "next-client-cookies/server";

// Components
import AlertModal from "@/components/common/AlertModal";

// Styles
import "@/styles/globals.css";

// Types
import { IPageProps } from "@/types/commonType";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: Pick<IPageProps, "params" | "children">) {
  const { resources } = await useTranslation(props.params.locale, i18nNamespaces);
  return (
    <html lang={props.params.locale}>
      <body>
        <CookiesProvider>
          <TranslationsProvider locale={props.params.locale} resources={resources} namespaces={i18nNamespaces}>
            <AlertModal />
            {props.children}
          </TranslationsProvider>
        </CookiesProvider>
        <div id="modal"></div>
      </body>
    </html>
  );
}
